import {Audio} from '@remotion/media';
import React from 'react';
import {Sequence, staticFile, useVideoConfig} from 'remotion';

/** Files in public/sfx, generated by scripts/generate-sound-effects.mjs. */
export type SfxName =
	| 'whoosh-gather'
	| 'pop-appear'
	| 'hop-boing'
	| 'crank-rattle'
	| 'coin-pop-out'
	| 'landing-squash'
	| 'chip-pop'
	| 'machine-drop'
	| 'pixel-run'
	| 'pixel-skid'
	| 'pixel-drop'
	| 'pixel-lock'
	| 'text-stamp'
	| 'pin-drop'
	| 'card-flip'
	| 'cable-tangle'
	| 'cable-snap-clean'
	| 'invoice-print'
	| 'coin-rain'
	| 'settle-chime'
	| 'paint-roller'
	| 'magic-swap'
	| 'arc-zip'
	| 'phone-ping'
	| 'qr-beep'
	| 'block-thud'
	| 'logo-shimmer'
	| 'footsteps-cartoon'
	| 'mg-whoosh'
	| 'mg-transition'
	| 'mg-tick'
	| 'mg-impact'
	| 'mg-riser'
	| 'mg-glitch'
	| 'mg-pop'
	| 'mg-sparkle'
	| 'mg-type'
	| 'mg-data'
	| 'mg-confirm'
	| 'mg-coin'
	| 'mg-bass-drop';

/** Mixed under the voice so effects add punch without masking words. */
const SFX_VOLUME = 0.45;

/** Plays a sound effect starting at scene time `at` (seconds). */
export const Sfx: React.FC<{name: SfxName; at: number; volume?: number}> = ({name, at, volume = 1}) => {
	const {fps} = useVideoConfig();
	return (
		<Sequence from={Math.max(0, Math.round(at * fps))} premountFor={fps}>
			<Audio src={staticFile(`sfx/${name}.mp3`)} volume={SFX_VOLUME * volume} />
		</Sequence>
	);
};
